Repository vinayakkulkarni/v-mapbox, pull requests merged in 2020-09, with the labels that each got.

#122 feat(ci): add `/rebase` workflow
  .github/workflows/rebase.yml
Labels: enhancement

#115 feat: add className option to popup
  docs/api/popup.md
  src/components/UI/Popup.vue
Labels: good first issue

#123 fix: add classes for popup
  src/components/UI/Popup.vue
Labels: bug, enhancement
