Repository vinayakkulkarni/v-mapbox, pull requests merged in 2020-10, with the labels that each got.

#141 fix: rtl issue
  src/components/map/GlMap.vue
Labels: bug

#142 chore: release v1.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug, enhancement

#145 fix(ci): update workflows
  .github/workflows/ci.yml
  .github/workflows/shipjs-trigger.yml
Labels: bug

#148 fix: failing `npm run build` in shipjs trigger
  .github/workflows/shipjs-trigger.yml
Labels: bug

#152 chore: fix shipjs action
  .github/workflows/shipjs-trigger.yml
Labels: bug

#176 fix: minor housekeeping
  .github/dependabot.yml
  .github/workflows/shipjs-trigger.yml
  package-lock.json
  package.json
Labels: bug, dependencies, enhancement

#179 fix: the `main` entry file was 404
  package.json
Labels: bug

#183 fix: css issue caused due to `sideEffects: false`
  build/rollup.config.js
  build/rollup.config.min.js
  package-lock.json
  package.json
  src/components/map/GlMap.vue
Labels: bug, dependencies, enhancement
