Repository vinayakkulkarni/v-mapbox, pull requests merged in 2020-06, with the labels that each got.

#8 fix: update pkg registry
  package.json
Labels: bug

#9 chore: release v1.0.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug

#10 fix: typo in docs
  docs/README.md
Labels: documentation

#12 fix: update typo in docs
  docs/README.md
Labels: bug, documentation

#13 feat: add maxWidth prop for popup
  docs/api/popup.md
  src/components/UI/Popup.vue
Labels: documentation, enhancement

#14 docs: add ES Module import css example
  docs/guide/README.md
  docs/guide/basemap.md
Labels: documentation

#15 refactor: update docs and homepage url
  docs/README.md
  docs/api/Layers/README.md
  docs/guide/composition.md
  docs/guide/controls.md
  docs/guide/layers&sources.md
  docs/guide/markers&popups.md
  docs/plugin_components/README.md
  docs/plugin_components/plugin_components_development.md
  package.json
Labels: bug, documentation

#18 refactor: update docs
  docs/README.md
Labels: documentation

#21 feat: add Code Of Conduct
  CODE_OF_CONDUCT.md
Labels: enhancement

#30 refactor: updated prettier config
  .prettierrc
  package-lock.json
  package.json
  prettier.config.js
Labels: enhancement

#31 fix: update docs for Popup open & close events
  docs/api/popup.md
Labels: bug, documentation

#32 fix: update README for Layers
  docs/api/Layers/README.md
Labels: bug, documentation

#33 chore: release v1.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug, documentation, enhancement

#34 fix(deps): clean lockfile
  package-lock.json
Labels: bug, dependencies

#35 chore: release v1.3.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug

#36 feat: add styleimagemissing event
  src/components/map/events.js
Labels: enhancement

#40 feat: enable jsconfig for better VSCode Intellisense
  jsconfig.json
Labels: enhancement
