Repository vinayakkulkarni/v-mapbox, pull requests merged in 2021-09, with the labels that each got.

#490 chore: release v1.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: new release 🥳

#492 fix: map container template ref not found
  src/components/map/mixins/withPrivateMethods.ts
Labels: bug

#493 chore: release v1.8.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug, new release 🥳

#502 chore: release v1.8.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: new release 🥳
