Repository vinayakkulkarni/v-mapbox, pull requests merged in 2021-05, with the labels that each got.

#374 chore: minor housekeeping
  .eslintrc.js
  .github/workflows/ci.yml
  .github/workflows/rebase.yml
  .github/workflows/shipjs-trigger.yml
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  README.md
  build/rollup.config.js
  build/rollup.config.min.js
  husky.config.js
  package-lock.json
  package.json
Labels: dependencies, enhancement, github_actions, javascript

#346 fix: typo deafult to default
  docs/guide/basemap.md
  src/components/UI/Popup.vue
Labels: documentation

#360 fix: add props reflecting Mapbox Control API
  docs/api/controls.md
  src/components/UI/controls/GeolocateControl.js
  src/components/UI/controls/NavigationControl.js
Labels: documentation, enhancement

#375 chore: release v1.7.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: new release 🥳
